Update scala.yml

diff --git a/.github/workflows/scala.yml b/.github/workflows/scala.yml
--- a/.github/workflows/scala.yml
+++ b/.github/workflows/scala.yml
@@ -33,9 +33,9 @@ jobs:
     #  # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
     - name: check task commands
       run: sbt tasks
+    - name: run checks
+      run: echo "$MAIN_CLASS" ; history; find . -name playground
     - name: run selected main
-      run: echo "$MAIN_CLASS" ; echo history
-    - name: run selected main
-      run: sbt runMain "$MAIN_CLASS" || echo "error running sbt runMain $MAIN_CLASS"
+      run: sbt runMain  "$MAIN_CLASS" || echo "error running sbt runMain $MAIN_CLASS"
     - name: Upload dependency graph
       uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
